kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: preprod-pvc
  namespace: preprod
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
